enabled: ~

nameOverride: "geo-addressing-spark-hook"

serviceAccount:
  annotations: { }

dataVintage:
  image:
    repository: bitnami/kubectl
    pullPolicy: Always
    tag: latest
    pullSecrets: [ ]