global:
  awsRegion: "us-east-1"
  nfs:
    fileSystemId: fileSystemId
    ## Create storage class as part of chart
    storageClass:
      enabled: true
      ## external storage class name if not created as part of chart
      name: ~

reference-data:
  config:
    pdxApiKey: "your-pdx-api-key"
    pdxSecret: "your-pdx-api-secret"
    dataConfigMap: "{\"verify-geocode\":{\"usa\":[\"Geocoding MLD US#United States#All USA#Spectrum Platform Data\",\"Geocoding NT Street US#United States#All USA#Spectrum Platform Data\",\"Geocoding Reverse PRECISELYID#United States#All USA#Spectrum Platform Data\"]}}"
    countries:
      - usa