apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geo-addressing-spark-preferences-configmap.name" . }}
  labels:
    {{- include "geo-addressing-spark-preferences-configmap.selectorLabels" . | nindent 4 }}
data:
  preferences.yaml: |
    {{- toYaml .Values.preferences | nindent 4 }}