{{- if not .Values.global.manualDataConfig.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "hook-{{ .Release.Name }}-sa"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/resource-policy": delete
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "geo-addressing-spark-hook.labels" . | nindent 4 }}
{{- end }}
---
{{- if not .Values.global.manualDataConfig.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "hook-{{ .Release.Name }}-role"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/resource-policy": delete
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    verbs:
      - create
      - update
      - patch
      - delete
      - get
      - watch
      - list
{{- end }}
---
{{- if not .Values.global.manualDataConfig.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "hook-{{ .Release.Name }}-role-binding"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/resource-policy": delete
subjects:
  - kind: ServiceAccount
    name: "hook-{{ .Release.Name }}-sa"
roleRef:
  kind: Role
  name: "hook-{{ .Release.Name }}-role"
  apiGroup: rbac.authorization.k8s.io
{{- end }}