{{- if not .Values.global.manualDataConfig.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-data-vintage-{{ (.Release.Revision | int) }}"
  labels:
    {{- include "geo-addressing-spark-hook.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/resource-policy": delete
spec:
  ttlSecondsAfterFinished: 50
  backoffLimit: 0
  template:
    metadata:
      name: "{{ .Release.Name }}-data-vintage-{{ (.Release.Revision | int) }}"
      labels:
        {{- include "geo-addressing-spark-hook.labels" . | nindent 8 }}
    spec:
      {{- with .Values.dataVintage.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data-vintage-scripts-volume
          configMap:
            name: "hook-{{ .Release.Name }}-config-map"
            defaultMode: 0777
        - name: geo-addressing-spark-host-volume
          persistentVolumeClaim:
            claimName: {{ include "geo-addressing-spark-hook-pvc.name" . }}
      restartPolicy: Never
      serviceAccountName: "hook-{{ .Release.Name }}-sa"
      containers:
        - name: data-vintage-job
          image: "{{ .Values.dataVintage.image.repository }}:{{ .Values.dataVintage.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.dataVintage.image.pullPolicy }}
          volumeMounts:
            - name: data-vintage-scripts-volume
              mountPath: /tmp/vintage-script
            - name: geo-addressing-spark-host-volume
              mountPath: {{ .Values.global.nfs.volumeMountPath }}
          command: [
             "/tmp/vintage-script/data-vintage.sh",
             "{{- .Values.global.nfs.volumeMountPath }}",
             "{{- .Values.global.nfs.addressingBasePath }}",
             "{{- .Values.global.nfs.autoCompleteBasePath }}",
             "{{- .Values.global.nfs.lookupBasePath }}",
             "{{- .Values.global.nfs.reverseBasePath }}",
             "vintages.properties",
             "{{ .Values.global.dataVintage.configMap.name }}",
             "{{ .Values.global.countries | join "," }}"
          ]
      terminationGracePeriodSeconds: 0
      {{- with .Values.global.spark.nodeSelector.driver }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}